export const SET_UART_CHARACTERISTIC = 'SET_UART_CHARACTERISTIC';
export const SAVE_BLOCKLY_XML = 'SAVE_BLOCKLY_XML';
export const SET_BLOCKLY_LIST = 'SET_BLOCKLY_LIST';
export const DELETE_BLOCKLY_XML = 'DELETE_BLOCKLY_XML';
