/** UART ACTION TYPES **/
export const SET_ROBOT_SERVICES = 'SET_ROBOT_SERVICES';

/** BLOCKLY ACTION TYPES **/
export const SAVE_BLOCKLY_XML = 'SAVE_BLOCKLY_XML';
export const SET_BLOCKLY_LIST = 'SET_BLOCKLY_LIST';
export const DELETE_BLOCKLY_XML = 'DELETE_BLOCKLY_XML';

/** ROBOT CONFIG ACTION TYPES **/
export const SET_ROBOT_CONFIG = 'SET_ROBOT_CONFIG';
export const UPDATE_ROBOT_CONFIG = 'UPDATE_ROBOT_CONFIG';

/** CONTROLLER ASSIGNMENTS ACTION TYPES **/
export const SET_ASSIGNMENTS = 'SET_ASSIGNMENTS';
export const ADD_BUTTON_ASSIGNMENT = 'ADD_BUTTON_ASSIGNMENT';
export const REMOVE_BUTTON_ASSIGNMENT = 'REMOVE_BUTTON_ASSIGNMENT';
